"""tes3.writer — Serialize TES3 record dicts back to binary.

The inverse of tes3.reader.  Takes the same list-of-dicts format produced by
read_file / read_bytes and emits bit-identical binary output.

Design
------
- Every subrecord dict MUST have a "raw" key (the verbatim bytes).
  "parsed" is informational only; the writer always uses "raw".
- Exception: subrecords generated by addon/builder.py may omit "raw" and
  supply only "parsed" (plus the owning record tag in a "_record_tag" hint).
  In that case the writer serializes from "parsed" using the schema.
- The TES3 header's num_records field is auto-updated to match the actual
  number of non-TES3 records before writing.

Usage
-----
    from tes3.reader import read_file
    from tes3.writer import write_file

    records = read_file("original.omwaddon")
    # ... modify records ...
    write_file(records, "modified.omwaddon")
"""

from __future__ import annotations

import struct
from pathlib import Path
from typing import Any

from .schema import (
    SUBRECORD_SCHEMAS,
    HedrSchema,
    SubrecordSchema,
    StringSchema,
)

RECORD_HEADER_FMT = struct.Struct("<4sIII")
SUBREC_HEADER_FMT = struct.Struct("<4sI")


# ---- public API -----------------------------------------------------------

def write_file(records: list[dict], path: str | Path) -> None:
    """Serialize records to a TES3 binary file."""
    data = write_bytes(records)
    Path(path).write_bytes(data)


def write_bytes(records: list[dict], update_num_records: bool = True) -> bytes:
    """Serialize a list of record dicts to bytes.

    Parameters
    ----------
    update_num_records:
        When True (default), recomputes and writes the num_records field in
        the TES3/HEDR subrecord — but ONLY if the current value in the parsed
        dict is 0 (i.e., a freshly-built record from AddonBuilder).
        Set to False for strict round-trip fidelity with existing files.
    """
    if update_num_records:
        records = _patch_num_records(records)

    parts: list[bytes] = []
    for rec in records:
        parts.append(_encode_record(rec))
    return b"".join(parts)


# ---- internal helpers -----------------------------------------------------

def _patch_num_records(records: list[dict]) -> list[dict]:
    """Return records with TES3/HEDR num_records set to len(non-TES3 records).

    Only patches if the HEDR parsed num_records is currently 0 (builder-generated).
    Leaves existing non-zero values untouched to preserve round-trip fidelity.
    """
    non_tes3 = sum(1 for r in records if r["tag"] != "TES3")
    patched = []
    for rec in records:
        if rec["tag"] == "TES3":
            new_subrecords = []
            for sr in rec["subrecords"]:
                if sr["tag"] == "HEDR":
                    current = sr.get("parsed", {})
                    if isinstance(current, dict) and current.get("num_records", 0) == 0:
                        sr = _patch_hedr_num_records(sr, non_tes3)
                new_subrecords.append(sr)
            rec = {**rec, "subrecords": new_subrecords}
        patched.append(rec)
    return patched


def _patch_hedr_num_records(sr: dict, num_records: int) -> dict:
    """Return a new HEDR subrecord dict with updated num_records."""
    raw = sr["raw"]
    if len(raw) < 300:
        raw = raw.ljust(300, b"\x00")
    raw = bytearray(raw)
    struct.pack_into("<I", raw, 296, num_records)
    new_sr = {**sr, "raw": bytes(raw)}
    if "parsed" in new_sr:
        new_sr["parsed"] = {**new_sr["parsed"], "num_records": num_records}
    return new_sr


def _encode_record(rec: dict) -> bytes:
    """Encode a single record dict to bytes."""
    tag = rec["tag"].encode("ascii").ljust(4, b"\x00")[:4]
    flags = rec.get("flags", 0)
    hdr1 = rec.get("hdr1", 0)

    payload_parts = [_encode_subrecord(sr, rec["tag"]) for sr in rec["subrecords"]]
    payload = b"".join(payload_parts)

    header = RECORD_HEADER_FMT.pack(tag, len(payload), hdr1, flags)
    return header + payload


def _encode_subrecord(sr: dict, record_tag: str) -> bytes:
    """Encode a single subrecord dict to bytes."""
    sr_tag = sr["tag"].encode("ascii").ljust(4, b"\x00")[:4]

    # Use raw bytes if available (round-trip fidelity)
    if "raw" in sr:
        data = sr["raw"]
    else:
        # Synthesize from parsed + schema (builder path)
        data = _serialize_from_parsed(record_tag, sr["tag"], sr.get("parsed"))

    header = SUBREC_HEADER_FMT.pack(sr_tag, len(data))
    return header + data


def _serialize_from_parsed(record_tag: str, sr_tag: str, parsed: Any) -> bytes:
    """Serialize a parsed value back to bytes using the schema."""
    schema = SUBRECORD_SCHEMAS.get((record_tag, sr_tag))

    if isinstance(schema, HedrSchema):
        return _encode_hedr(parsed)

    if isinstance(schema, StringSchema):
        if isinstance(parsed, str):
            return parsed.encode(schema.encoding) + b"\x00"
        return b"\x00"

    if isinstance(schema, SubrecordSchema):
        return _encode_struct(schema, parsed)

    # Fallback: if parsed is a string, encode it
    if isinstance(parsed, str):
        return parsed.encode("latin-1") + b"\x00"
    if isinstance(parsed, (bytes, bytearray)):
        return bytes(parsed)
    return b""


def _encode_hedr(parsed: dict) -> bytes:
    """Encode HEDR from a parsed dict."""
    if not parsed:
        return b"\x00" * 300
    buf = bytearray(300)
    version = parsed.get("version", 1.3)
    file_type = parsed.get("file_type", 0)
    struct.pack_into("<fI", buf, 0, version, file_type)
    company = parsed.get("company", "")
    if isinstance(company, str):
        company = company.encode("latin-1")
    buf[8:8 + min(32, len(company))] = company[:32]
    description = parsed.get("description", "")
    if isinstance(description, str):
        description = description.encode("latin-1")
    buf[40:40 + min(256, len(description))] = description[:256]
    struct.pack_into("<I", buf, 296, parsed.get("num_records", 0))
    return bytes(buf)


def _encode_struct(schema: SubrecordSchema, parsed: dict) -> bytes:
    """Pack a struct-schema subrecord from a dict."""
    if not parsed:
        size = struct.calcsize(schema.fmt)
        return b"\x00" * size
    values = []
    fmt_chars = _split_fmt(schema.fmt)
    for field, fmt_char in zip(schema.fields, fmt_chars):
        val = parsed.get(field, 0)
        # If the format char expects bytes (s), encode strings
        if "s" in fmt_char and isinstance(val, str):
            width = int(fmt_char.replace("s", ""))
            val = val.encode("latin-1").ljust(width, b"\x00")[:width]
        values.append(val)
    try:
        return struct.pack(schema.fmt, *values)
    except struct.error:
        size = struct.calcsize(schema.fmt)
        return b"\x00" * size


def _split_fmt(fmt: str) -> list[str]:
    """Split a struct format string into per-field format specifiers."""
    import re
    # Strip endian prefix
    body = fmt.lstrip("<>!=@")
    parts = re.findall(r"\d*[xcbBhHiIlLqQfdspP]", body)
    return parts
